language: node_js

node_js:
  - "12"
  - "13"

install:
  - npm install

stages:
  - test
  - coverage

test:
  - npm run lint

coverage:
  script: npm run coverage
  on:
    repo: beda-software/aidbox-react
